logging:
  file:
    name: ./log/application.log
  level:
    root: DEBUG
    org:
      jdbc: TRACE
      web: DEBUG

spring:
    datasource:
      url: jdbc:postgresql://${IAM_DB_HOST}:${IAM_DB_PORT}/${IAM_DB_NAME}
      username: ${IAM_DB_USERNAME}
      password: ${IAM_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 30
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    mvc:
      contentnegotiation:
        default-content-type: "application/json"
        media-types:
          html: "text/html"
          json: "application/json"
          xml: "application/xml"

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
              client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
              scope:
                - email
                - profile
#            github:
#              client-id: ${GITHUB_OAUTH2_CLIENT_ID}
#              client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
#              scope:
#                - email
#                - profile
